  object Typos{
  def handleTypos(input: String): String = {
  val commonTypos = Map(
    // General words
    "hello" -> List("helo", "hallo", "heloo", "hel", "elo", "heo", "helloo", "hlo"),
    "hi" -> List("hiii", "hai", "hhi", "hii", "hee", "hy"),
    "how" -> List("hoow", "hwo", "howw", "ho", "howare", "howr"),
    "are" -> List("ar", "re", "rae", "aare", "arre"),
    "you" -> List("yuo", "yo", "yoo", "yu", "youu"),
    "what" -> List("wht", "waht", "wat", "whaat", "whatt", "whut"),
    "is" -> List("si", "iss", "iis", "s", "iz"),
    "the" -> List("teh", "th", "tge", "hte", "thhe", "da"),
    "food" -> List("fod", "foood", "fud", "foood", "fod", "fode"),
    "cuisine" -> List("cusine", "cuisin", "cuisne", "cuisene", "cuisnie", "quisine"),
    "bye" -> List("bi","bey", "byee"),
    "vegetarian" -> List("vegitarian", "vegeterian", "veggie", "vegatarian", "veggitarian"),
    "ingredients" -> List("ingridients", "ingreedients", "ingrediants", "ingridiants", "ingrs"),
    "quiz" -> List("quizz", "quize", "quz", "quizzze", "qiz"),
    "dish" -> List("dsh", "dissh", "dich", "dissh", "dishh"),   
    "egyptian" -> List("egyption","egiptian", "egiptian", "egypitan", "egyptian", "egypitian"),
    "french" -> List("frensh", "frenche", "frnch", "frensh", "frnch"),
    "lebanese" -> List("lebanes", "lebanesee", "lebanes", "lebanessee", "lebanes"),
    "korean" -> List("koreean", "koreaan", "koreean", "koreean", "korean"),
    "quit" -> List("quitt", "quitt", "quitte", "quitt", "quit","quizt","qui","qut"),
    "sure" -> List("shure", "suree", "surr", "shure", "shur"),
    "please" -> List("plese", "pleas", "pleese", "pleas", "plese"),
    "thank" -> List("thx", "thnks", "thanx", "thxk", "thx"),
    "thanks" -> List("thx", "thnks", "thanx", "thxk", "thx"),
    "welcome" -> List("welcom", "welcme", "welcom", "welccome", "welcom"),
    "recipe" -> List("recpie", "recip", "recipie", "recpiee", "recipie","reciepe?", "recipie"),
    "make" -> List("mak", "maek", "maake", "mke", "mae"),
    "cook" -> List("cok", "cokk", "cokie", "cokkk", "cok"),
    "tell" -> List("tel", "tll", "tll", "tll", "tll"),
    "about" -> List("abou", "abaut", "abouut", "abouut", "abou"),
    "yes" -> List("yea", "yess", "yees", "yesss", "ye","y"),
    "no" -> List("noo", "n", "nooo", "nno", "nnoo"),
    "good" -> List("god", "gud", "goood", "gooodd", "gud", "godd"),
    "bad" -> List("badd", "badde", "baad", "bda", "bd"),
    "sorry" -> List("sory", "srry", "sorr", "soory", "soryy"),
    "ask" -> List("as", "askk", "aks", "askc", "asck", "askk"),
    "are" -> List("ar", "re", "rae", "aare", "arre"),
    "and" -> List("ad", "andd", "an", "andd", "annd"),


    // Egyptian food terms
    "koshari" -> List("koshary", "koshare", "koshari", "kushari", "kosheri","koshaarii","koshri","koushari"),
    "ful medames" -> List("foul medames", "ful medammes", "fool medames", "ful mudammes","ful mdames"),
    "molokhia" -> List("mulukhiya", "molohiya", "molokhiya", "mulukhia", "melokhia","mouloukheia"),
    "taameya" -> List("tameya", "ta'meya", "tamiya", "taameia", "taamya","taamia"),
    "mahshi" -> List("mashi", "mahshy", "mahshe", "mashy", "mahshie","mhshy"),
    "fatta" -> List("fata", "fattah", "fatah", "fatte", "fataa"),
    "basbousa" -> List("basboosa", "basbosa", "basboosah", "basbousah", "basboussa", "basboosha", "basboosaa"),
    "konafa" -> List("kunafa", "kanafa", "knafeh", "knafa", "konafah", "kanefa", "konapha"),
    "hamam mahshi" -> List("hamam mashy", "hamam mahshy", "hamam mashshi", "hamam mahshe", "hamam mahshie", "hamam mahchi", "hamam mashie"),
    "shakshuka" -> List("shakshouka", "shakshoka", "shakshukah", "shakshoka", "shakshukha", "shakshoca", "shaqshuka"),
    "bamia" -> List("bamya", "bameya", "bamiya", "bamyah", "bameyah", "bamiah", "bamiaa"),
    "fattah bil laban" -> List("fatta bil laban", "fatah bil laban", "fattah bi laban", "fatteh bil laban", "fatah bi laban", "fata bil laban", "fatat bil laban"),
    "roz bel laban" -> List("ruz bel laban", "roz bil laban", "ruz bil laban", "rooz bel laban", "rooz bil laban", "roze bel laban", "roz bal laban"),
    "samak mashwy" -> List("samak mashwi", "samak mashawi", "samak mashwey", "samak mashoe", "samak mashwe", "samak mashue", "samak mashwiya"),
    "batates bil forno" -> List("batatis bil forno", "batata bil forno", "batates bel forno", "batatis bel forno", "batata bel forno", "batatiz bil forno", "batates bilforno"),
    "lentil soup" -> List("lental soup", "lentel soup", "lentel soop", "lentil soop", "lentil suop", "lentol soup", "lentyl soup"),
    "hawawshi" -> List("hawawshy", "hawawshie", "hawawche", "hawawchy", "hawawchee", "hawawshee", "hawawchi"),
    "atayef" -> List("ataief", "atayf", "ataif", "atayif", "ataief", "atayaff", "atayev","atyf"),

    // French food terms
    "ratatouille" -> List("ratatoulle", "ratatuil", "ratatouile", "ratatoille", "ratatoullie", "ratatoolie", "ratatoulli", "ratatoille", "ratatoul"),
    "coq au vin" -> List("coc au vin", "coqauvain", "coq auvine", "coke au vin", "kok au vin", "coq au van", "cok au vin", "coq auvin", "coq-o-vin"),
    "quiche lorraine" -> List("kish lorraine", "quish lorraine", "quiche loraine", "quiche lorain", "qiche lorraine", "kwiche lorraine", "quiche-lorraine", "quichelorraine", "quiche lorein"),
    "tarte tatin" -> List("tart tatin", "tarte tatine", "tartetatin", "tart tatine", "tarte-tatin", "tartatatine", "tarte tatim", "tart taatin", "tarte tatene"),
    "pain au chocolat" -> List("pan au chocolat", "paino chocolat", "pain au chocalat", "pain au choclat", "pain au choco", "pain au chockolat", "pane au chocolat", "pain-auchocolat", "panochocolat"),
    "boeuf bourguignon" -> List("beouf bourguignon", "boeuf bourginon", "boef bourguignon", "boeuf burgignon", "boeuf bourgignon", "boeuf-bourguignon", "beef bourguignon", "boeuf borgignon", "bœuf bourguignon"),
    "croissant" -> List("crossant", "croisant", "croisantt", "croissont", "croiissant", "crosant", "croussant", "croissaint", "croiassant"),
    "cassoulet" -> List("casoulet", "cassulet", "cassulet", "casoulette", "cassulait", "cassoullet", "cassoulate", "cassulett", "cassolay"),
    "crème brûlée" -> List("creme brulee", "creme brulay", "cream brulee", "cremé brûlée", "creme-brulee", "creme brulé", "kreme brulee", "crème brule", "cremebrulee"),
    "soupe à l'oignon" -> List("soup a l'oignon", "soupe al oignon", "soupe a loignon", "soup à l'oignon", "soupe-a-loignon", "soupe a l onion", "soupel'oignon", "soup l’oignon", "soupe loignon"),
    "éclair" -> List("eclair", "eclaire", "éclaire", "ecliar", "eklair", "eclari", "eclere", "éclai", "eclairr"),
    "salade niçoise" -> List("salad nicoise", "salade nicois", "salade-nicoise", "salade nicsoise", "salade nicoisse", "salade-niçoise", "salad niçois", "salade niçwaise", "saladnicoise"),
    "clafoutis" -> List("clafouti", "claffoutis", "clafouty", "clafoutie", "claffouti", "clafoutiss", "clafutis", "claffoutys", "clafouti’s"),
    "gratin dauphinois" -> List("gratin dauphinoise", "gratin daphinois", "gratin-dauphinois", "gratin dauphinoi", "graten dauphinois", "gratin dauphinose", "graten dophinois", "gratin dauphinoisse", "grattin dauphinois"),
    "galette des rois" -> List("gallet des rois", "galette desroys", "galet des rois", "galette-des-rois", "gallate des rois", "galette des roi", "galette de rois", "galette desroys", "galeette des rois"),
    "steak frites" -> List("steakfrite", "steak-frite", "steak fritt", "steek frites", "steak freets", "steak frittes", "stek frites", "steak fritez", "steak fritz"),
    "crêpes" -> List("crepe","crepes", "crèpes", "crape", "crepps", "crêpe", "crepés", "krepes", "crapés", "crrepes"),
    "mousse au chocolat" -> List("mousse o chocolat", "mouse au chocolat", "mousse au chocalat", "mousseauchocolat", "mousse au choco", "moussa au chocolat", "mous au chocolat", "mousse-oh-chocolat", "mousse chocolat"),
    "mille-feuille" -> List("millefeuille", "mille feuille", "mille-foy", "milfeuille", "mille fuille", "mil feuille", "mille fouille", "mille-feulie", "millfeuille","milfeuile"),

    //Korean food terms
    "bibimbap" -> List("bibimpap", "bibibmap", "bibmbap", "bibinbap", "bibimmbap", "bibimbup", "bibinpap", "bebimbap", "bibimbop"),
    "kimchi" -> List("kimchee", "kimchy", "kimci", "kymchi", "kimhci", "kimshi", "kimhi", "quimchi", "kimchii"),
    "japchae" -> List("japche", "japchea", "japchaee", "japcha", "japchei", "japchay", "japchey", "japchye", "japchaie"),
    "bulgogi" -> List("bulgogee", "bulgogii", "bulgoki", "bulgogey", "bulghogi", "bulgoji", "bolgogi", "bulgougi", "bulgoogi"),
    "tteokbokki" -> List("teokbokki", "tteokboki", "ddeokbokki", "tteokboky", "tteobbokki", "ttekbokki", "tteokbokie", "ttokbokki", "tteokbokkie"),
    "samgyeopsal" -> List("samgyupsal", "samgyopsal", "samgyepsal", "samgyopsel", "samgyeopsel", "samgyupsul", "samgyeosalp", "samgeopsal", "samgyeobsal"),
    "haemul pajeon" -> List("haemul pajun", "haemool pajeon", "haemul pageon", "haemul-pajeon", "haemul pajean", "haemul pajeoen", "haemulpajeon", "haemul pajen", "haemul pajon"),
    "soondubu jjigae" -> List("sundubu jjigae", "soondubu chigae", "soondubu jjigaee", "soondubu-jjigae", "sundubu-jjigae", "soondubujjigae", "soondubo jjigae", "soondubu jigae", "soondubu jjjigae"),
    "kimchi jjigae" -> List("kimchi chigae", "kimchijjigae", "kimchi-jjigae", "kimchi jigae", "kimchi jjigai", "kimchi jiggae", "kimchi jigai", "kimchi jjjigae", "kimchee jjigae"),
    "mandu" -> List("mandoo", "mando", "mandou", "mandhu", "manndu", "mandu dumplings", "mandu korean", "mandu’s", "mandyoo"),
    "naengmyeon" -> List("naengmyun", "naengmyon", "naeng-myeon", "naeng myeon", "naengmyoen", "naegmyeon", "naengmeyon", "naengmyeonn", "naengmyun"),
    "dakgalbi" -> List("dakgalbee", "dak galbi", "dak-galbi", "dakkalbi", "dakgalbii", "dakgalvy", "dakgalpy", "dakgalpi", "dakalbi"),
    "galbi" -> List("kalbi", "galbee", "galby", "galvi", "gahlbi", "galbei", "galbie", "galbii", "gallbi"),
    "hotteok" -> List("hoddeok", "hottok", "hoteok", "hotok", "hotdeok", "hotteock", "hotteo", "hottoek", "hottoeok"),
    "gyeran jjim" -> List("gyeranjjim", "gyeran jjeem", "gyeran jim", "gyeran-jjim", "gyerang jjim", "gyeran jimm", "gyeran jeem", "gyeran jjime", "gyeran jjmm"),
    "hobakjuk" -> List("hobakjuk", "hobagjuk", "hobak jook", "hobak-juk", "hobakjuk", "hobajuk", "hobakjok", "hobakjuuk", "hobakjukc"),
    "bingsu" -> List("bingsoo", "bing su", "bing-su", "bingsuu", "bingxoo", "bingsue", "bingshu", "bingus", "bingsū"),
    "gamja jorim" -> List("gamjajorim", "gamja jorrim", "gamja-jorim", "gamja jorime", "gamja jorrime", "gamja jorimm", "gamja jorimn", "gamza jorim", "gamja jorin"),
    "bossam" -> List("bosam", "bo ssam", "bossem", "bossamm", "bossom", "bozzam", "bosamm", "bboossam", "boszam"),

    //Lebanese food terms
    "tabbouleh" -> List("tabbouli", "tabboulii", "tabouli", "tabuleh", "taboule", "taboulé", "tabouleh", "taboolah", "tabbouleh’s"),
    "hummus" -> List("hoummus", "hommus", "hummous", "hummus dip", "humus", "humous", "hummoush", "hommous", "humoush"),
    "kibbeh" -> List("kibe", "kibbi", "kibbih", "kebbah", "kibeh", "kibbah", "kibbee", "kibbey", "kibbie"),
    "fattoush" -> List("fatush", "fattosh", "fatoosh", "fatush", "fatushe", "fattoush salad", "fattoushje", "fatosh", "fattoshe"),
    "shawarma" -> List("shwarma", "shawerma", "shawermah", "shawirma", "shwarma", "shawarmas", "shawarmae", "shwarma"),
    "mujadara" -> List("mujaddara", "mojadara", "mujadara", "mujadara", "mujderah", "mujadrra", "mojadarra", "mujadarra", "mujadrah"),
    "kafta" -> List("kaftah", "kaftan", "kaftah", "kaftah kebab", "kafta kebab", "kaftaah", "kaftaaa", "kafta grill", "kaftash"),
    "manakish" -> List("manakesh", "manakesh", "manaqish", "manakiche", "manakeesh", "manakish bread", "manakch", "manakesh bread", "manakishesh"),
    "falafel" -> List("falaffel", "falafell", "falafel", "felfel", "faleffel", "felafel", "falaffel", "falfel", "faafel"),
    "sambousek" -> List("sambousak", "sambusak", "sambusik", "sambusak", "sambosak", "sambosik", "sambousik", "sambouseque", "sambouscek"),
    "rekakat" -> List("rikakat", "riqakat", "recakat", "rekakat", "recakat", "raikat", "rikkat", "rekat", "rekekat"),
    "lahm bi ajeen" -> List("lahm bi ajeene", "lahm bie ajeen", "lahm be ajin", "lahmbiajin", "lahmbiajen", "lahm bi ajen", "lahmbiageen", "lahm bih ajeen"),
    "moghrabieh" -> List("maghrabieh", "mghrabeh", "mgharabieh", "moghrabiye", "maghrabiyyah", "mghrabie", "mghrabiye", "mohgrabe", "moghrabii"),
    "arnabeet mekle" -> List("arnabit makleh", "arnabeet mekleh", "arnabeet makeleh", "arnabeet makal", "arnabeet mekleh", "arnabeetmkleh", "arnabeet meklee", "arnabeetmekleh", "arnabeet mekali"),
    "batata harra" -> List("batatah harrah", "batat harra", "batat harrra", "batata harrah", "batta harra", "battata harra", "bata harrra", "batath hara", "batath harrah"),
    "warak enab" -> List("warak anab", "warak anab", "warake enab", "warak enabb", "warak enap", "warake nab", "warae nab", "warakenab", "warakenaab"),
    "shish tawook" -> List("shishtawook", "shishtawuk", "shishtawok", "shishtawok", "shish tawook", "shish tawuq", "shish tawki", "sishtawook", "shishtwok"),
    "bazella w riz" -> List("bazella with riz", "bazilla w riz", "bazillaw riz", "bazella riz", "bazalla w riz", "bazellaw reez", "bazella wriz", "bazilaw riz", "bazellaz riz"),
    "knefeh" ->List("knafa","konafa","knfa","kounafa","kenafahh","koonafa","kunafa","kounafahh"),

    // ==== General CUISINE INGREDIENTS ====
    "rice" -> List("ryce", "ricce", "ricc", "rize", "ric", "rise", "raice", "rci"),
    "zucchini" -> List("zucchinni", "zuchinni", "zuchinni", "zucchinni", "zukini", "zuchini"),
    "eggs" -> List("egs", "egges", "eggss", "egggs", "eggsy","egg"),
    "eggplant" -> List("egplant", "eggplnt", "eggpplant", "eggplnate", "eggnplant"),
    "tomatoes" -> List("tomatos", "tomatoe", "tomatoss", "tomatoe", "tomatoess"),
    "onion" -> List("onion", "onionns", "onionn", "onins", "onins"),
    "garlic" -> List("garlik", "garlc", "garlics", "garlikc", "garli"),
    "olive oil" -> List("oliv oil", "olvie oil", "olivve oil", "oliv oil", "olivoil"),
    "herbs" -> List("herbbes", "herbes", "herbss", "herbz", "herbbz"),
    "cream" -> List("creem", "crema", "creamz", "creemz", "cream"),
    "raisins" -> List("raisinss", "raisin", "raisens", "rasins", "raisinz"),
    "sugar" -> List("suggar", "suger", "sugr", "sugars", "suggar"),
    "mushroom" -> List("mushroms", "mushrums", "mushrooms", "mushroomz", "mushrom", "mushrm"),
    "salt" -> List("saalt", "salt", "sallt", "saltt", "slt"),
    "pepper" -> List("peper", "peppar", "peppre", "peppur", "peppper"),
    "lettuce" -> List("lettucee", "lettucce", "lettuse", "lettace", "lettuice"),
    "beef" -> List("beefy", "beff", "beefs", "beeff", "beefsteak", "beefd", "beffy"),
    "carrot" -> List("carots", "carrotts", "carotts", "carots", "carrotss"),
    "chickpeas" -> List("chickpees", "chikpeas", "chichpeas", "chikpeass", "chicpeas","cichkpees","cickpeas"),
    "cucumber" -> List("cukmber", "cucmber", "cucmber", "cuccumber", "cucumer","kukumber"),
    "radish" -> List("rdish", "radishh", "radsh", "raadiish", "radishs","radich","raadish"),
    "tomato sauce" -> List("tomto sauce", "tomato suce", "tomaato souce", "tomatosose", "tometo sos"),
    "lemon juice" -> List("lemmon juice", "lemn juice", "lemonn juice", "lemmonn juice", "lemon-juice","lemon jice","lemoun juci"),
    "parsley" -> List("parslly", "prsly", "parslye", "parssley", "parslee","parzlee","prasli","persaly","pursley"),
    "cilantro" -> List("cilantroo", "cilantro", "cilentro", "cilantroh", "cilantor"),
    "spices" -> List("spyces", "spices", "spicess", "spycess", "speces"),
    "yogurt" -> List("yoghurt", "yogourt", "yogurt", "yoghourt", "yogurtt"),
    "semolina" -> List("semolena", "semolinaa", "semolinna", "semolna", "semolena"),
    "sugar syrup" -> List("sugar syrp", "sugr syrupp", "sugrsyrp", "sugar sirup", "ssugaar ssirupp","sugarsyrrup"),
    "cheese" -> List("cheeze", "chese", "cheesee", "cheez", "chesee"),

  


    // ===== Egyptian CUISINE INGREDIENTS =====
    "lentils" -> List("lentiles", "lentills", "lentls", "lentilss", "lentl"),
    "pasta" -> List("pastaa", "paste", "psta", "passtaa", "passta"),
    "fried onions" -> List("fryed onions", "frying onions", "friedonions", "frid onions", "fried onion"),
    "fava beans" -> List("fava beens", "favabeans", "fava beens", "fava beanz", "favabeenz"),
    "coconut" -> List("cocnut", "coconutt", "cocconut", "cocunut", "coconutty"),
    "shredded pastry" -> List("shreddedpastry", "shredded pastry", "shreded pastr", "shreddedpastrey", "shredded pasterry"),
    "nuts" -> List("nutts", "nutes", "nutsz", "nutz", "nut"),
    "okra" -> List("okra", "okraaa", "okras", "okras", "okrah"),
    "lamb" -> List("lam", "lambb", "lambe", "lamby", "lambchop"),
    "bread" -> List("bred", "breade", "breadd", "breaad", "brad"),
    "bell peppers" -> List("bellpeppers", "bell pepper", "bel peppers", "bel peppers", "bellpepar"),
    "crispy bread" -> List("crispybread", "crispy bread", "crispybred", "crispy bread", "crispybred"),
    "minced meat" -> List("mince meat", "minceeed meat", "minsed meat", "miced meat", "mincemeat"),
    "spiced minced meat" -> List("spices mincemeat", "spiced mincemeat", "spice minced meat", "spicedminced meat", "spicd minced meat"),
    "pigeon" -> List("pidgeon", "pigin", "pigeons", "pidgen", "pidgen"),
    "pita bread" -> List("pitabread", "pita-bread", "pittabread", "pitabred", "pitteh bread"),

    // ===== French CUISINE INGREDIENTS =====
    "red wine" -> List("redwine", "redwines", "red-wine", "redwineee", "reed wine","rd win","red win"),
    "bacon" -> List("baconn", "baconb", "baconn", "backon", "bacons","bacn"),
    "thyme" -> List("thime", "thym", "tyme", "thymme", "thymn"),
    "pie crust" -> List("piecrust", "pie crust", "crust pie", "crustpie", "piecrustt"),
    "apples" -> List("applse", "appless", "applz", "applez", "applles"),
    "butter" -> List("buter", "buttr", "buttere", "butt", "butr"),
    "pastry" -> List("pastery", "pastryy", "pastrie", "pastry", "pastriee"),
    "flour" -> List("flur", "flwer", "flourr", "flouer", "flouwr"),
    "yeast" -> List("yeastt", "yees", "yeast", "yest", "yeas"),
    "milk" -> List("milkk", "mylk", "milke", "mylkk", "milkys"),
    "dark chocolate" -> List("darkchocolate", "dark chocolate", "dark choclate", "darkchoco", "dark choc"),
    "water" -> List("watr", "waterr", "waterr", "wate", "wattter"),
    "potatoes" -> List("potatos", "potattoes", "potatotes", "pottatoes", "potatoss"),
    "steak" -> List("steaks", "steaks", "steek", "staek", "steakyy"),
    "cinnamon" -> List("cinnemon", "cinnaman", "cinamon", "cinnmon", "cinammon"),
    "frangipane" -> List("franjipane", "frangipene", "frangipain", "frangipene", "frangipan"),
    "puff pastry" -> List("puffpastry", "puff pastry", "puffpastery", "pufpastry", "puffpasterry"),
    "powdered sugar" -> List("powderedsugar", "powderedsugars", "powderedsuger", "powderedugar", "powderedsugar"),
    "white beans" -> List("whitebeans", "whitbeens", "white beans", "whtebeens", "whitesbeans"),
    "duck" -> List("dick", "duckk", "dukk", "duke", "duc"),
    "sausage" -> List("sausge", "sausages", "sausage", "sausgges", "sausgees"),
    "anchovies" -> List("anchovis", "anchoevis", "anchovys", "anovhies", "anchovys"),
    "tuna" -> List("tunna", "tonna", "tunaa", "tunaa", "tuna"),
    "hard-boiled eggs" -> List("hardboiledeggs", "hardboiledegs", "hardboiledegg", "hardboildedeggs", "hardboiled eggss"),

    // ===== Korean CUISINE INGREDIENTS =====
    "spinach" -> List("spinich", "spinch", "spenach", "spynach", "spinaach"),
    "gochujang" -> List("gochujung", "gochujangh", "gochujanggg", "gochujangn", "gochujng"),
    "napa cabbage" -> List("nappa cabbage", "napa cabage", "napa cabbages", "nappa cabbge", "napacabbage"),
    "ginger" -> List("gingr", "gengger", "gengerr", "gingr", "gingr", "ginger", "gingrr"),
    "gochugaru" -> List("gochugaroo", "gochugar", "gochuguru", "gochugaru", "gochugura"),
    "fish sauce" -> List("fishsauce", "fsh sauce", "fissh sauce", "fishes sauce", "fishsauces"),
    "soy sauce" -> List("soysauce", "soysauces", "soysoss", "soyssaue", "soy sause", "soysase", "soyosauce"),
    "glass noodles" -> List("glassnoodles", "glass noodle", "glassnoodless", "glas noodles", "glassnoddles"),
    "sesame oil" -> List("sesameoil", "sesameoill", "sesam oil", "sesamoil", "sesam oil"),
    "green onion" -> List("greenonion", "grennonion", "green onions", "greonion", "greenon"),
    "seafood" -> List("seafoods", "seafod", "seefood", "seafodd", "seafoo", "seafoodss"),
    "soft tofu" -> List("softtofu", "softtofuu", "sof tofu", "soft tofu", "softoo tofu"),
    "tofu" -> List("tofus", "toof", "tofoo", "tofu", "tofuu"),
    "pork belly" -> List("porkbelly", "porkbely", "porkbell", "porkbellyy", "pork beely", "pork bell", "porkbellyyy"),
    "dumpling wrappers" -> List("dumplingwrapper", "dumplingwappers", "dumplngwrappers", "dumplingwppers", "dumplingwraps"),
    "buckwheat noodles" -> List("buckwheatnoodles", "buckwheatnoodls", "buckwheat noodles", "buckwheatnoodls", "buckwhetnoodles"),
    "pear" -> List("pearss", "peaar", "per", "peer", "pears"),
    "mustard" -> List("mustarrd", "mustar", "mustrad", "mustard", "mustarddd"),
    "vinegar" -> List("vinegarrr", "vineger", "viner", "vinega", "vinegarr"),
    "chicken" -> List("chiken", "chikkens", "chikens", "chikeny", "chikk"),
    "sweet potato" -> List("sweetpotato", "sweetpotatos", "sweeet potato", "sweetpotatos", "sweetptoato"),
    "ssamjang" -> List("ssamjangg", "ssamjangg", "ssamjang", "ssamjaang", "ssamjangs"),
    "cabbage" -> List("cabbagee", "cabbge", "cabbahe","cabge","cubbage"),

    // ===== Lebanese CUISINE INGREDIENTS =====
    "bulgur" -> List("blgur", "bulgurr", "bulguur", "bulguer", "bulgr","buljer","blgr"),
    "green onion" -> List("green onin", "grn onion", "greenn onionss", "gree nonionn", "green onions","greenn onionss"),
    "mint" -> List("minnts", "mints", "minnt", "mient", "mintt","mnt","miint"),
    "tahini" -> List("tahni", "tahhin", "tahina", "tehina", "tahine","tahinah"),
    "ground beef" -> List("grond beef", "grounded beef", "ground bef", "gruund beefss", "grnd beef"),
    "pine nuts" -> List("pine nts", "pin nuts", "pinenutt", "pin nuts", "pinenutts","pinee nut"),
    "crispy pita" -> List("crispy pitt", "crispy pitta", "crispe pita", "crispy pitta", "crspy pta","pita"),
    "sumac" -> List("sumc", "sumack", "sumak", "sumaac", "summac","smac"),
    "ground lamb" -> List("grnd lamb", "ground lmb", "ground laam", "grond lambb", "grnd lamb"),
    "za'atar" -> List("za atar", "zaatar", "zattar", "zaattarr", "zataar"),
    "flatbread" -> List("fltbread", "flatbrads", "flatberd", "fslttbreadd", "flt bred"),
    "sesame seeds" -> List("sesam seeds", "sesame seds", "sesam seeed", "ssame seed", "sesame seeds"),
    "cumin" -> List("cumn", "comin", "cummn", "cummim", "cuminn"),
    "coriander" -> List("coriandr", "corriander", "corianderr", "corriand", "coryander"),
    "phyllo dough" -> List("phylo dough", "phyllodough", "filo dough", "philo dough", "filodough"),
    "cauliflower" -> List("caulflower", "cauliflour", "cauloflowr", "caulifower", "cauliflowerr"),
    "chili" -> List("chil", "chilly", "chilis", "chilii", "chilli"),
    "grape leaves" -> List("grap leaves", "grapeleave", "grape leaves", "grapeleaves", "grapleaves"),
    "minced beef" -> List("minc beef", "mincedbeef", "mincedbeefs", "mincedbeff", "mincebeef"),
    
  )
  val lowerInput = input.toLowerCase

  // Find the correct word if the input matches any typo
  // find is higher function for Map 
  commonTypos.find { 
    case (correct, typos) =>typos.foldLeft(false) { (found, typ) =>
    if (found) true else typ.toLowerCase == lowerInput} }.map(_._1).getOrElse(input)
 }
  }